---
deployment:
  tasks:
    - export DEPLOYPATH=/home/buselmei/public_html/preview-skinprotocolrx.buselmeier.com
    - /bin/cp -RF /home/buselmei/public_html/preview-skinprotocolrx.buselmeier.com/dist/. $DEPLOYPATH
